### ISSUE TITLE
Despawning Bug pls help

### ISSUE THREAD

**Issue by ZippingBoat9588** [Tobias-2006/ClearLag#2]
Armor Stands will despawn after the clear how i can do it that they will not despawn?

**Comment by tobiaskirchmaier** [comment]
What entity plugin are you using? @ZippingBoat9588

**Comment by ZippingBoat9588** [comment]
Umm what? Entity? 
Mobs or Armor stand?

**Comment by ZippingBoat9588** [comment]
@Tobias-2006 For Armor Stands i use PM Armor Stand

**Comment by tobiaskirchmaier** [comment]
1. Open the config file (`path/to/your/server/plugin_data/ClearLag/config.yml`)

2. Add `"Armor Stand"` to the `exceptions` tag.

```yml
exceptions:
  - "Armor Stand"
```

@ZippingBoat9588
