### ISSUE TITLE
It clears the mobs from the spawners

### ISSUE THREAD

**Issue by PSYCHO1512** [Tobias-2006/ClearLag#3]
When i use it and restart the server it clears the mobs from the spawners and spawners become empty

**Comment by Tobias-2006** [comment]
What spawner/entity plugin do you use?

**Comment by PSYCHO1512** [comment]
Burger spawy

**Comment by Tobias-2006** [comment]
Can you send me the version of BurgerSpawners you have on Discord? I downloaded one for PM4, but the entities in the spawners disappear after a rejoin, not after a clearlag.

**Comment by PSYCHO1512** [comment]
I didnt try rejoin but after restart the clear and someone told me that its clearlag issue

**Comment by PSYCHO1512** [comment]
And i think theres only one veraion of burger spawners for pm4

**Comment by Tobias-2006** [comment]
Try if the problem also occurs without ClearLag and please let me know. I think it is the spawner plugin.

**Comment by PSYCHO1512** [comment]
Ok

**Comment by PSYCHO1512** [comment]
I cant try it rk i wil try it later and tell you

**Comment by PSYCHO1512** [comment]
Whats your discord

**Comment by Tobias-2006** [comment]
My discord is tobias14#1903. I don't think it's ClearLag, because the entities in the spawner are not entities, but a tile, which is not affected by ClearLag.

My tests showed that the error also occurred without the ClearLag plugin. The spawners seem to work again after a right click on them.

**Comment by PSYCHO1512** [comment]
I will try that

**Comment by PSYCHO1512** [comment]
thanks for the help i might pay my dev to fix this issue of burger spawner
