### ISSUE TITLE
How to change time between alert messages

### ISSUE THREAD

**Issue by Diedman9T** [Tobias-2006/ClearLag#4]
I wanna change time between messages. 
I need to set something like that:
First message - 5 min (before cleaning)
Second - 1 min
Third - 10 sec

How can I do it?

**Comment by tobiaskirchmaier** [comment]
This is currently not possible because the times are fixed in the source code. May come in the next update.

**Comment by Diedman9T** [comment]
Maybe u can tell me where exactly I can change it in source code?

**Comment by tobiaskirchmaier** [comment]
They are set in https://github.com/Tobias-2006/ClearLag/blob/7d43ce0769ce9da109df6c6f3a02ad148597c3f4/src/task/ClearTask.php#L15

**Comment by Diedman9T** [comment]
Thanks a lot!
